### ISSUE TITLE
Update Security Protocol to TLS 1.2

### ISSUE THREAD

**Issue by dfallou** [kfrancis/ChargifyDirectSampleDotNet#1]
The code (and your demo site) don't work unless you specify the new TLS 1.2 security protocol. I just added the line:

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

To the application_start and it worked fine. Just a note in case anyone else was running in to this issue.

**Comment by TimS-** [comment]
Failing for me too and on the Azure hosted sample - added an issue to the main repo :-/

**Comment by kfrancis** [comment]
Oh, I don't think I dealt with this library in terms of the Tls changes. I'll take a look.

**Comment by kfrancis** [comment]
I'm so sorry this took so long. It's been updated.
